spring.application.name=Todo
spring.datasource.url=jdbc:postgresql://dpg-d88agertqb8s7388hu20-a.oregon-postgres.render.com:5432/todo_xo7a
spring.datasource.username=todo_xo7a_user
spring.datasource.password=zjGGPSNeq0Rfc1Wy9Ez2v1Qj5DcE6tO4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true