spring.application.name=Todo
spring.datasource.url=jdbc:postgresql://postgres1:7FBvf41pnIW1uKlmkAyNqlekQ6gXYL6W@dpg-d87tfacm0tmc73861a90-a.virginia-postgres.render.com/tododb_k02i
spring.datasource.username=postgres1
spring.datasource.password=7FBvf41pnIW1uKlmkAyNqlekQ6gXYL6W

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true